# Generated by Django 2.1.1 on 2018-12-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=1000)),
                ('titulo_puntuacion', models.IntegerField(default=0)),
                ('resumen', models.TextField(default='', max_length=10000)),
                ('resumen_puntuacion', models.IntegerField(default=0)),
                ('planteamiento', models.TextField(default='', max_length=10000)),
                ('planteamiento_puntuacion', models.IntegerField(default=0)),
                ('justificacion', models.TextField(default='', max_length=10000)),
                ('justificacion_puntuacion', models.IntegerField(default=0)),
                ('resultados', models.TextField(default='', max_length=10000)),
                ('resultados_puntuacion', models.IntegerField(default=0)),
                ('marco', models.TextField(default='', max_length=10000)),
                ('marco_puntuacion', models.IntegerField(default=0)),
                ('general', models.TextField(default='', max_length=10000)),
                ('general_puntuacion', models.IntegerField(default=0)),
                ('especifico', models.TextField(default='', max_length=10000)),
                ('especifico_puntuacion', models.IntegerField(default=0)),
                ('variables', models.TextField(default='', max_length=10000)),
                ('variables_puntuacion', models.IntegerField(default=0)),
                ('tipo', models.TextField(default='', max_length=10000)),
                ('tipo_puntuacion', models.IntegerField(default=0)),
                ('universo', models.TextField(default='', max_length=10000)),
                ('universo_puntuacion', models.IntegerField(default=0)),
                ('seleccion', models.TextField(default='', max_length=10000)),
                ('seleccion_puntuacion', models.IntegerField(default=0)),
                ('etica', models.TextField(default='', max_length=10000)),
                ('etica_puntuacion', models.IntegerField(default=0)),
                ('analisis', models.TextField(default='', max_length=10000)),
                ('analisis_puntuacion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('resumen', models.TextField(default='', max_length=10000)),
                ('planteamiento', models.TextField(default='', max_length=10000)),
                ('justificacion', models.TextField(default='', max_length=10000)),
                ('resultados', models.TextField(default='', max_length=10000)),
                ('resultados_puntuacion', models.IntegerField(default=0)),
                ('marco', models.TextField(default='', max_length=10000)),
                ('general', models.TextField(default='', max_length=10000)),
                ('especifico', models.TextField(default='', max_length=10000)),
                ('variables', models.TextField(default='', max_length=10000)),
                ('tipo', models.TextField(default='', max_length=10000)),
                ('universo', models.TextField(default='', max_length=10000)),
                ('seleccion', models.TextField(default='', max_length=10000)),
                ('etica', models.TextField(default='', max_length=10000)),
                ('analisis', models.TextField(default='', max_length=10000)),
            ],
        ),
    ]
