# Generated by Django 2.1.1 on 2018-12-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0002_auto_20181219_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='residencia',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='revisor',
            name='residencia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
